GavinArechiga/Monster-Mash

Monster Mash/Monster Mash/Assets/Scenes/CharacterController.unity
Monster Mash/Monster Mash/Assets/Scripts/Controller1.cs
Monster Mash/Monster Mash/Assets/Scripts/input_handler.cs
Monster Mash/Monster Mash/Assets/input action map.inputactions
Monster Mash/Monster Mash/ProjectSettings/EditorBuildSettings.asset

Added keyboard support in input_handler

Keyboard :-)

---

Monster Mash/Monster Mash/Assets/Monster Parts/Arms/Arm 1/Arm 1 - Attack.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Legs/Leg 1/Leg 1 - Backward Brace.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Legs/Leg 1/Leg 1 - Backward Brace.anim.meta
Monster Mash/Monster Mash/Assets/Monster Parts/Legs/Leg 1/Leg 1 - Forward Brace.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Legs/Leg 1/Leg 1 - Forward Brace.anim.meta
Monster Mash/Monster Mash/Assets/Monster Parts/Legs/Leg 1/Leg 1.controller
Monster Mash/Monster Mash/Assets/Scenes/Animation Room.unity
Monster Mash/Monster Mash/Assets/animationRoom.cs
Monster Mash/Monster Mash/Assets/animationRoom.cs.meta
Monster Mash/Monster Mash/Assets/attackObject.cs
Monster Mash/Monster Mash/Assets/monsterAttackTest.cs

Completed a lot of testing and implimintation with our current animation system and I am ready to start working on a more solid foundation for our game

End of Animation Test 1

---

Monster Mash/Monster Mash/Assets/Prefabs/Cursor.prefab
Monster Mash/Monster Mash/Assets/Prefabs/Cursor.prefab.meta
Monster Mash/Monster Mash/Assets/Prefabs/Game Manager.prefab
Monster Mash/Monster Mash/Assets/Prefabs/Game Manager.prefab.meta
Monster Mash/Monster Mash/Assets/Prefabs/player2 cc.prefab
Monster Mash/Monster Mash/Assets/Prefabs/player2 cc.prefab.meta
Monster Mash/Monster Mash/Assets/Prefabs/player2.prefab
Monster Mash/Monster Mash/Assets/Prefabs/player2.prefab.meta
Monster Mash/Monster Mash/Assets/Scenes/CameraMagic.unity
Monster Mash/Monster Mash/Assets/Scenes/CameraMagic.unity.meta
Monster Mash/Monster Mash/Assets/Scenes/CharacterController.unity
Monster Mash/Monster Mash/Assets/Scenes/ConveyorBelt.unity
Monster Mash/Monster Mash/Assets/Scripts/BattleCamera.cs
Monster Mash/Monster Mash/Assets/Scripts/BattleCamera.cs.meta
Monster Mash/Monster Mash/Assets/Scripts/ConveyorBelt.cs
Monster Mash/Monster Mash/Assets/Scripts/CursorConveyorSelection.cs
Monster Mash/Monster Mash/Assets/Scripts/CursorConveyorSelection.cs.meta
Monster Mash/Monster Mash/Assets/Scripts/CustomCursor.cs
Monster Mash/Monster Mash/Assets/Scripts/CustomCursor.cs.meta
Monster Mash/Monster Mash/Assets/Scripts/OnConveyor.cs
Monster Mash/Monster Mash/Assets/Scripts/input_handler.cs
Monster Mash/Monster Mash/Assets/input action map.inputactions

Battle Camera is here!!!
ther might also be some conveyor belts because I forgor to push the last few changes as well!!

Battle Camera

---

Monster Mash/Monster Mash/Assets/Monster Parts/Arms/Arm 1/Arm 1 - Tuck In.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Arms/Arm 1/Arm 1 - Tuck In.anim.meta
Monster Mash/Monster Mash/Assets/Monster Parts/Arms/Arm 1/Arm 1.controller
Monster Mash/Monster Mash/Assets/Monster Parts/Heads/Head 1/Head 1 - Tuck In.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Heads/Head 1/Head 1 - Tuck In.anim.meta
Monster Mash/Monster Mash/Assets/Monster Parts/Heads/Head 1/Head 1.controller
Monster Mash/Monster Mash/Assets/Monster Parts/Legs/Leg 1/Leg 1 - Tuck In.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Legs/Leg 1/Leg 1 - Tuck In.anim.meta
Monster Mash/Monster Mash/Assets/Monster Parts/Legs/Leg 1/Leg 1.controller
Monster Mash/Monster Mash/Assets/Monster Parts/Monster.controller
Monster Mash/Monster Mash/Assets/Monster Parts/Torsos/Torso 1/Torso 1 - Tuck In.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Torsos/Torso 1/Torso 1 - Tuck In.anim.meta
Monster Mash/Monster Mash/Assets/Monster Parts/Torsos/Torso 1/Torso 1.controller
Monster Mash/Monster Mash/Assets/Monster Parts/rollLeft.anim
Monster Mash/Monster Mash/Assets/Monster Parts/rollLeft.anim.meta
Monster Mash/Monster Mash/Assets/Monster Parts/rollRight.anim
Monster Mash/Monster Mash/Assets/Monster Parts/rollRight.anim.meta
Monster Mash/Monster Mash/Assets/Player.prefab
Monster Mash/Monster Mash/Assets/Scenes/CharacterController.unity
Monster Mash/Monster Mash/Assets/Scenes/Limb Test Room.unity
Monster Mash/Monster Mash/Assets/Scenes/Test Rooms/Animation System.unity
Monster Mash/Monster Mash/Assets/Scripts/monsterAttackSystem.cs
Monster Mash/Monster Mash/Assets/Scripts/monsterPart.cs

Got rolls working for double jumps and platform phasing, groundwork established for a possible rollout move as well

Animation Rolling + Input Set Up

---

Monster Mash/Monster Mash/Assets/input action map.inputactions

i deleted a control scheme because I accidentally destroyed all life when i did that oops sorry

Input system FIXED

---

Monster Mash/Monster Mash/Assets/Scenes/HealthSystemMagicIsGathering.unity
Monster Mash/Monster Mash/Assets/Scenes/HealthSystemMagicIsGathering.unity.meta
Monster Mash/Monster Mash/Assets/Scripts/Health.cs
Monster Mash/Monster Mash/Assets/Scripts/Health.cs.meta

I wrote THE NICEST lil' health script >:(

The Nicest Lil' Health Script

---

Monster Mash/Monster Mash/Assets/Scenes/Test Rooms/VFX Test Room.unity
Monster Mash/Monster Mash/Assets/Scenes/Test Rooms/VFX Test Room.unity.meta

I added a VFX test room for the VFX team for a small Github Demo!

Added VFX Scene

---

Monster Mash/Monster Mash/Assets/Scenes/Test Rooms/VFX Test Room.unity

Tester plane

---

Monster Mash/Monster Mash/Assets/Prefabs/Monster 1.prefab
Monster Mash/Monster Mash/Assets/Prefabs/Monster 1.prefab.meta
Monster Mash/Monster Mash/Assets/Prefabs/PlayerController.prefab
Monster Mash/Monster Mash/Assets/Scripts/Controller1.cs
Monster Mash/Monster Mash/Assets/Scripts/input_handler.cs
Monster Mash/Monster Mash/Assets/Scripts/monsterPart.cs
Monster Mash/Monster Mash/Assets/input action map.inputactions

Finishing Up!

---

Monster Mash/Monster Mash/Assets/Prefabs/PlayerController.prefab
Monster Mash/Monster Mash/Assets/Scripts/Controller1.cs
Monster Mash/Monster Mash/Assets/Scripts/input_handler.cs
Monster Mash/Monster Mash/Assets/Scripts/monsterAttackSystem.cs
Monster Mash/Monster Mash/Assets/Scripts/monsterPart.cs

Pushing run capabilities.
Fixed attack bug

Run & Attack

---

Monster Mash/Monster Mash/Assets/Monster Parts/Arms/Arm 1/Arm 1 - Downward Attack.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Arms/Arm 1/Arm 1 - Forward Attack.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Arms/Arm 1/Arm 1 - Upward Attack.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Arms/Arm 1/Arm 1.controller
Monster Mash/Monster Mash/Assets/Monster Parts/Heads/Head 1/Head 1.controller
Monster Mash/Monster Mash/Assets/Monster Parts/Legs/Leg 1/Leg 1 - Backward Attack.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Legs/Leg 1/Leg 1 - Forward Attack.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Legs/Leg 1/Leg 1 - Grounded Down Attack.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Legs/Leg 1/Leg 1 - Land.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Legs/Leg 1/Leg 1 - Leading Jump.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Legs/Leg 1/Leg 1 - Trailing Jump.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Legs/Leg 1/Leg 1.controller
Monster Mash/Monster Mash/Assets/Monster Parts/Monster.controller
Monster Mash/Monster Mash/Assets/Monster Parts/Torsos/Torso 1/Torso 1 - Tuck In.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Torsos/Torso 1/Torso 1.controller
Monster Mash/Monster Mash/Assets/Monster Parts/flipLefttoRight.anim
Monster Mash/Monster Mash/Assets/Monster Parts/flipRighttoLeft.anim
Monster Mash/Monster Mash/Assets/Monster Parts/squashLand - Face Left.anim
Monster Mash/Monster Mash/Assets/Monster Parts/squashLand - Face Right.anim
Monster Mash/Monster Mash/Assets/Prefabs/Monster 1.prefab
Monster Mash/Monster Mash/Assets/Prefabs/PlayerController.prefab
Monster Mash/Monster Mash/Assets/Scenes/ControllerAnimationsWorkPlease.unity
Monster Mash/Monster Mash/Assets/Scenes/Test Rooms/Animation System.unity
Monster Mash/Monster Mash/Assets/Scripts/monsterAttackSystem.cs
Monster Mash/Monster Mash/Assets/Scripts/monsterPart.cs

For the most part this batch of changes was about fixing some visual bugs with animations and with making them more responsive

Animation Debugging

---

Monster Mash/Monster Mash/Assets/Monster Parts/Eyes/Eye 2/Eye 2 - Attack.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Eyes/Eye 2/Eye 2 - Attack.anim.meta
Monster Mash/Monster Mash/Assets/Monster Parts/Eyes/Eye 2/Eye 2 - Brace.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Eyes/Eye 2/Eye 2 - Brace.anim.meta
Monster Mash/Monster Mash/Assets/Monster Parts/Eyes/Eye 2/Eye 2 - Hit.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Eyes/Eye 2/Eye 2 - Hit.anim.meta
Monster Mash/Monster Mash/Assets/Monster Parts/Eyes/Eye 2/Eye 2 - Idle.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Eyes/Eye 2/Eye 2 - Jump.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Eyes/Eye 2/Eye 2 - Jump.anim.meta
Monster Mash/Monster Mash/Assets/Monster Parts/Eyes/Eye 2/Eye 2 - Land.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Eyes/Eye 2/Eye 2 - Land.anim.meta
Monster Mash/Monster Mash/Assets/Monster Parts/Eyes/Eye 2/Eye 2.controller
Monster Mash/Monster Mash/Assets/Scenes/Test Rooms/Ani Room.unity

Eye 2 anim part 2

---

Monster Mash/Monster Mash/Assets/Monster Parts/Legs/Leg 1/Leg 1.controller
Monster Mash/Monster Mash/Assets/Scenes/Stages/The Backyard.unity
Monster Mash/Monster Mash/Assets/Settings/URP-HighFidelity.asset

Tweaked some shadow details and cameras for stage layout reasons, worked on establishing some tools for greybox useage

Greyboxes and Rendering

---

Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 1/SnowHunter.meta
Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 1/SnowHunter/MonsterMash - Wing 1 Variant.prefab
Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 1/SnowHunter/MonsterMash - Wing 1 Variant.prefab.meta
Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 1/SnowHunter/MonsterMash - Wing 1.prefab
Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 1/SnowHunter/MonsterMash - Wing 1.prefab.meta
Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 1/SnowHunter/MonsterMash_wing01_RigUpdated.fbx.meta
Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 1/SnowHunter/Wing 1 - Brace.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 1/SnowHunter/Wing 1 - Brace.anim.meta
Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 1/SnowHunter/Wing 1 - Fall.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 1/SnowHunter/Wing 1 - Fall.anim.meta
Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 1/SnowHunter/Wing 1 - Glide.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 1/SnowHunter/Wing 1 - Glide.anim.meta
Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 1/SnowHunter/Wing 1 - Hit.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 1/SnowHunter/Wing 1 - Hit.anim.meta
Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 1/SnowHunter/Wing 1 - Idle Fly.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 1/SnowHunter/Wing 1 - Idle Fly.anim.meta
Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 1/SnowHunter/Wing 1 - Idle Grounded.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 1/SnowHunter/Wing 1 - Idle Grounded.anim.meta
Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 1/SnowHunter/Wing 1 - Jump.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 1/SnowHunter/Wing 1 - Jump.anim.meta
Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 1/SnowHunter/Wing 1 - Land.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 1/SnowHunter/Wing 1 - Land.anim.meta
Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 1/SnowHunter/Wing 1 - Soft Landing.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 1/SnowHunter/Wing 1 - Soft Landing.anim.meta
Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 1/SnowHunter/Wing 1 - Tuck In.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 1/SnowHunter/Wing 1 - Tuck In.anim.meta
Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 1/SnowHunter/Wing 1.controller
Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 1/SnowHunter/Wing 1.controller.meta
Monster Mash/Monster Mash/Assets/Scenes/Animation Room.unity

I'm hoping all wing animations are to everyone's satisfaction !

Wing 1 Animations

---

Monster Mash/Monster Mash/Assets/Monster Parts/Eyes/Eye 2/Eye 2 - Attack.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Eyes/Eye 2/Eye 2 - Fall.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Eyes/Eye 2/Eye 2 - Fall.anim.meta
Monster Mash/Monster Mash/Assets/Monster Parts/Eyes/Eye 2/Eye 2 - Hit.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Eyes/Eye 2/Eye 2 - Idle.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Eyes/Eye 2/Eye 2 - Jump.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Eyes/Eye 2/Eye 2 - Old Idle.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Eyes/Eye 2/Eye 2 - Old Idle.anim.meta
Monster Mash/Monster Mash/Assets/Monster Parts/Eyes/Eye 2/Eye 2.controller
Monster Mash/Monster Mash/Assets/Scenes/Test Rooms/Ani Room.unity

Eye 2 animation final

---

Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 1/Wing 1 - Big Flap.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 1/Wing 1 - Brace.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 1/Wing 1 - Fall.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 1/Wing 1 - Glide.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 1/Wing 1 - Idle Fly.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 1/Wing 1 - Idle Grounded.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 1/Wing 1 - Jump.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 1/Wing 1 - Land.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 1/Wing 1 - Running.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 1/Wing 1 - Running.anim.meta
Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 1/Wing 1 - Soft Landing.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 1/Wing 1 - Tuck In.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 1/Wing 1.controller
Monster Mash/Monster Mash/Assets/Scenes/Animation Room.unity

Polishing existing wing animations and a running animation has been added !

Wing1 Fixes

---

Monster Mash/Monster Mash/Assets/Body Connections.mat
Monster Mash/Monster Mash/Assets/Body Connections.mat.meta
Monster Mash/Monster Mash/Assets/Monster Parts/Arms/Arm 1/Monster Mash - Arm 1.prefab
Monster Mash/Monster Mash/Assets/Monster Parts/Legs/Leg 1/Monster Mash - Leg 1.prefab
Monster Mash/Monster Mash/Assets/Monster Parts/Mouths/Mouth 2/Monster Mash - Mouth 2_Rigged.prefab
Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 1/MonsterMash - Wing 1 Variant.prefab
Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 1/Wing 1.controller
Monster Mash/Monster Mash/Assets/Scenes/Test Rooms/Animation System.unity
Monster Mash/Monster Mash/Assets/Scripts/animationRoom.cs
Monster Mash/Monster Mash/Assets/Scripts/monsterAttackSystem.cs
Monster Mash/Monster Mash/Assets/Scripts/monsterPart.cs
Monster Mash/Monster Mash/Assets/autoLimb_Connection.cs
Monster Mash/Monster Mash/Assets/autoLimb_Connection.cs.meta
Monster Mash/Monster Mash/Assets/groundedLimbArea.cs
Monster Mash/Monster Mash/Assets/groundedLimbArea.cs.meta
Monster Mash/Monster Mash/Assets/monsterPartReference.cs
Monster Mash/Monster Mash/Assets/monsterPartReference.cs.meta
Monster Mash/Monster Mash/ProjectSettings/TagManager.asset

Added in a neat framework that will auto connect limbs on game start and have each piece work exactly as intended. Works as both an Animation tool for faster testing as well as for the basics of Build A Scare functionality.

Auto Limb Attachment

---

Monster Mash/Monster Mash/Assets/Scenes/Stages/The Beastdome.unity

Worked on creating the blockout for Cybutgh City. Parts are angled downward for better presentation.

Blockout for Cyburgh City

---

Monster Mash/Monster Mash/Assets/Scenes/Stages/The Beastdome.unity

Unroated the blockout- rotated the camera instead

Unroated Cyburgh City Blockout

---

Monster Mash/Monster Mash/Assets/Monster Parts/Eyes/Eye 2/Eye 2 - Attack.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Eyes/Eye 3/Eye 3 - Brace.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Eyes/Eye 3/Eye 3 - Brace.anim.meta
Monster Mash/Monster Mash/Assets/Monster Parts/Eyes/Eye 3/Eye 3 - Fall.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Eyes/Eye 3/Eye 3 - Fall.anim.meta
Monster Mash/Monster Mash/Assets/Monster Parts/Eyes/Eye 3/Eye 3 - Hit.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Eyes/Eye 3/Eye 3 - Hit.anim.meta
Monster Mash/Monster Mash/Assets/Monster Parts/Eyes/Eye 3/Eye 3 - Idle.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Eyes/Eye 3/Eye 3 - Idle.anim.meta
Monster Mash/Monster Mash/Assets/Monster Parts/Eyes/Eye 3/Eye 3 - Jump.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Eyes/Eye 3/Eye 3 - Jump.anim.meta
Monster Mash/Monster Mash/Assets/Monster Parts/Eyes/Eye 3/Eye 3 - Land.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Eyes/Eye 3/Eye 3 - Land.anim.meta
Monster Mash/Monster Mash/Assets/Monster Parts/Eyes/Eye 3/Eye 3.controller
Monster Mash/Monster Mash/Assets/Monster Parts/Eyes/Eye 3/Eye 3.controller.meta
Monster Mash/Monster Mash/Assets/Monster Parts/Eyes/Eye 3/MM - Eye 3.prefab
Monster Mash/Monster Mash/Assets/Monster Parts/Eyes/Eye 3/MM - Eye 3.prefab.meta
Monster Mash/Monster Mash/Assets/Scenes/Test Rooms/Ani Room.unity

Eye 3 Animations

---

Monster Mash/Monster Mash/Assets/Scenes/Test Rooms/Animation System.unity
Monster Mash/Monster Mash/Assets/Scripts/animationRoom.cs
Monster Mash/Monster Mash/Assets/Scripts/monsterPart.cs

Using a lot of the framework from my autolimb system I made this week, I made a system for easier animation testing where the animation room will walk you through a more streamlined way of managing inputs and attacks with monster parts

Animation Room Overhaul

---

Monster Mash/Monster Mash/Assets/Prefabs/PlayerController.prefab
Monster Mash/Monster Mash/Assets/Scripts/Controller1.cs
Monster Mash/Monster Mash/Assets/Scripts/input_handler.cs

that was tuff
attack bugs are simply removed because I need Halp

OY I FIXED THE BUGS :')

---

Monster Mash/Monster Mash/Assets/Scenes/Animation Room.unity

reput the prefab into hierarchy, has the same animator as well. everything is functioning on my end. I didn't delete the faulty one, just in case deleting anything also made any errors.

arm 4 troubleshooting pt.2

---

Monster Mash/Monster Mash/Assets/Monster Parts/Horns/Horn 3/Horn 3 - Fireball.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Horns/Horn 3/Horn 3 - Neutral.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Tails.meta
Monster Mash/Monster Mash/Assets/Monster Parts/autoLimb_Connection.cs
Monster Mash/Monster Mash/Assets/Monster Parts/monsterAttackSystem.cs
Monster Mash/Monster Mash/Assets/Monster Parts/monsterPart.cs
Monster Mash/Monster Mash/Assets/Monster Parts/projectile.cs
Monster Mash/Monster Mash/Assets/Test Rooms/Gavin/Monster Workshop/Animations/Attack Room Camera.controller
Monster Mash/Monster Mash/Assets/Test Rooms/Gavin/Monster Workshop/Animations/Camera - Close Range Left.anim
Monster Mash/Monster Mash/Assets/Test Rooms/Gavin/Monster Workshop/Animations/Camera - Close Range Left.anim.meta
Monster Mash/Monster Mash/Assets/Test Rooms/Gavin/Monster Workshop/Animations/Camera - Close Range Right.anim
Monster Mash/Monster Mash/Assets/Test Rooms/Gavin/Monster Workshop/Animations/Camera - Close Range Right.anim.meta
Monster Mash/Monster Mash/Assets/Test Rooms/Gavin/Monster Workshop/Animations/Camera - Long Range Left.anim
Monster Mash/Monster Mash/Assets/Test Rooms/Gavin/Monster Workshop/Animations/Camera - Long Range Left.anim.meta
Monster Mash/Monster Mash/Assets/Test Rooms/Gavin/Monster Workshop/Animations/Camera - Long Range Right.anim
Monster Mash/Monster Mash/Assets/Test Rooms/Gavin/Monster Workshop/Animations/Camera - Long Range Right.anim.meta
Monster Mash/Monster Mash/Assets/Test Rooms/Gavin/Monster Workshop/Animations/Camera - Medium Range Left.anim
Monster Mash/Monster Mash/Assets/Test Rooms/Gavin/Monster Workshop/Animations/Camera - Medium Range Left.anim.meta
Monster Mash/Monster Mash/Assets/Test Rooms/Gavin/Monster Workshop/Animations/Camera - Medium Range Right.anim
Monster Mash/Monster Mash/Assets/Test Rooms/Gavin/Monster Workshop/Animations/Camera - Medium Range Right.anim.meta
Monster Mash/Monster Mash/Assets/Test Rooms/Gavin/Monster Workshop/Monster Workshop.unity
Monster Mash/Monster Mash/Assets/Test Rooms/Gavin/Monster Workshop/Scripts/animationRoom.cs
Monster Mash/Monster Mash/Assets/Test Rooms/Gavin/Monster Workshop/Test Objects/White Grid Background.mat

Basics for how projectiles work, based on Horn 3 fireball attack

Projectile System

---

Monster Mash/Monster Mash/Assets/Player Controller/InputSystem.inputsettings.asset
Monster Mash/Monster Mash/Assets/Player Controller/PlayerCursor.prefab
Monster Mash/Monster Mash/Assets/Player Controller/PlayerCursor.prefab.meta
Monster Mash/Monster Mash/Assets/Player Controller/input action map.inputactions
Monster Mash/Monster Mash/Assets/Quickplay.unity
Monster Mash/Monster Mash/Assets/Scripts/MultiplayerScripts.meta
Monster Mash/Monster Mash/Assets/Scripts/MultiplayerScripts/CharacterSelectIcon.cs
Monster Mash/Monster Mash/Assets/Scripts/MultiplayerScripts/CharacterSelectIcon.cs.meta
Monster Mash/Monster Mash/Assets/Scripts/MultiplayerScripts/MultiplayerCursor.cs
Monster Mash/Monster Mash/Assets/Scripts/MultiplayerScripts/MultiplayerCursor.cs.meta
Monster Mash/Monster Mash/Assets/Scripts/MultiplayerScripts/MultiplayerJoinManager.cs
Monster Mash/Monster Mash/Assets/Scripts/MultiplayerScripts/MultiplayerJoinManager.cs.meta
Monster Mash/Monster Mash/Assets/Scripts/MultiplayerScripts/StageSelectIcon.cs
Monster Mash/Monster Mash/Assets/Scripts/MultiplayerScripts/StageSelectIcon.cs.meta
Monster Mash/Monster Mash/Assets/Test Rooms/Jeremy - Multiplayer Demo.meta
Monster Mash/Monster Mash/Assets/Test Rooms/Jeremy - Multiplayer Demo/MultiplayerDemoScene.unity
Monster Mash/Monster Mash/Assets/Test Rooms/Jeremy - Multiplayer Demo/MultiplayerDemoScene.unity.meta
Monster Mash/Monster Mash/ProjectSettings/EditorBuildSettings.asset
Monster Mash/Monster Mash/ProjectSettings/TagManager.asset

-Working on moving UI elements with controllers for character select
-The base structure of character select and stage select has been added

Multiplayer Demo Update 1

---

Monster Mash/Monster Mash/Assets/Monster Parts/Arms/Arm 1/Animations/Arm 1 - Downward Attack - Neutral.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Arms/Arm 1/Animations/Arm 1 - Upward Attack - Neutral.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Arms/Arm 1/Animations/Arm 1.controller

Removed some animation function keyframes that popped up during demo

Matt Demo Test

---

Monster Mash/Monster Mash/Assets/Monster Parts/Arms/Arm 1/Animations/Arm 1.controller
Monster Mash/Monster Mash/Assets/Monster Parts/Arms/Arm 2/Animations/Arm 2 - New.controller
Monster Mash/Monster Mash/Assets/Monster Parts/Arms/Arm 7/Animations/Arm 7 - Downward Attack -  Neutral.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Arms/Arm 7/Animations/Arm 7 - Forward Attack - Heavy.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Arms/Arm 7/Animations/Arm 7 - Forward Attack - Neutral.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Arms/Arm 7/Animations/Arm 7 - Forward Attack - Wind Up.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Arms/Arm 7/Animations/Arm 7 - Upward Attack - Neutral.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Arms/Arm 7/Animations/Arm 7.controller
Monster Mash/Monster Mash/Assets/Test Rooms/Matt/MattsWorkshop.unity

Mattworkship

---

Monster Mash/Monster Mash/Assets/BAS NewOrEdit.unity
Monster Mash/Monster Mash/Assets/BuildAScare.unity
Monster Mash/Monster Mash/Assets/Scripts/BuildAScare/BAS_NewOrLoad_Select.cs
Monster Mash/Monster Mash/Assets/Scripts/BuildAScare/TypeSelectorTabs.cs
Monster Mash/Monster Mash/Assets/Scripts/BuildAScare/TypeSelectorTabs.cs.meta
Monster Mash/Monster Mash/Assets/Scripts/ScenesManager.cs
Monster Mash/Monster Mash/ProjectSettings/EditorBuildSettings.asset

Added ScrollView w/ Tabs to scene.
- Currently not functioning correctly with objects, will need to find alternative with sprites

BuildAScareUpdate 240204

---

Monster Mash/Monster Mash/Assets/BuildAScare.unity
Monster Mash/Monster Mash/Assets/Scripts/BuildAScare/TypeSelectorTabs.cs
Monster Mash/Monster Mash/Assets/Scripts/CameraRotZoom.cs
Monster Mash/Monster Mash/Assets/Scripts/CameraRotZoom.cs.meta

Added correct placement of torso to scene as well as proper camera rotation.

Updated BuildAScare

---

Monster Mash/Monster Mash/Assets/Player Controller/PlayerInputAsset.prefab
Monster Mash/Monster Mash/Assets/Scripts/MultiplayerScripts/CharacterSelectIcon.cs
Monster Mash/Monster Mash/Assets/Scripts/MultiplayerScripts/MultiplayerCursor.cs
Monster Mash/Monster Mash/Assets/Scripts/MultiplayerScripts/MultiplayerJoinManager.cs
Monster Mash/Monster Mash/Assets/Scripts/MultiplayerScripts/PlayerSpawnManager.cs
Monster Mash/Monster Mash/Assets/Scripts/input_handler.cs
Monster Mash/Monster Mash/Assets/Test Rooms/Jeremy - Multiplayer Demo/GreyboxMaterials.meta
Monster Mash/Monster Mash/Assets/Test Rooms/Jeremy - Multiplayer Demo/GreyboxMaterials/BlueGlass.mat
Monster Mash/Monster Mash/Assets/Test Rooms/Jeremy - Multiplayer Demo/GreyboxMaterials/BlueGlass.mat.meta
Monster Mash/Monster Mash/Assets/Test Rooms/Jeremy - Multiplayer Demo/GreyboxMaterials/BrownMat.mat
Monster Mash/Monster Mash/Assets/Test Rooms/Jeremy - Multiplayer Demo/GreyboxMaterials/BrownMat.mat.meta
Monster Mash/Monster Mash/Assets/Test Rooms/Jeremy - Multiplayer Demo/GreyboxMaterials/GreenGlass.mat
Monster Mash/Monster Mash/Assets/Test Rooms/Jeremy - Multiplayer Demo/GreyboxMaterials/GreenGlass.mat.meta
Monster Mash/Monster Mash/Assets/Test Rooms/Jeremy - Multiplayer Demo/GreyboxMaterials/GreyMat.mat
Monster Mash/Monster Mash/Assets/Test Rooms/Jeremy - Multiplayer Demo/GreyboxMaterials/GreyMat.mat.meta
Monster Mash/Monster Mash/Assets/Test Rooms/Jeremy - Multiplayer Demo/GreyboxMaterials/RedGlass.mat
Monster Mash/Monster Mash/Assets/Test Rooms/Jeremy - Multiplayer Demo/GreyboxMaterials/RedGlass.mat.meta
Monster Mash/Monster Mash/Assets/Test Rooms/Jeremy - Multiplayer Demo/GreyboxMaterials/YellowGlass.mat
Monster Mash/Monster Mash/Assets/Test Rooms/Jeremy - Multiplayer Demo/GreyboxMaterials/YellowGlass.mat.meta
Monster Mash/Monster Mash/ProjectSettings/TagManager.asset

Updated Character Select

---

Monster Mash/Monster Mash/Assets/Player Controller/MonsterVisualPrefab.prefab
Monster Mash/Monster Mash/Assets/Player Controller/MonsterVisualPrefab.prefab.meta
Monster Mash/Monster Mash/Assets/Player Controller/MultiPlayerPlayer.prefab
Monster Mash/Monster Mash/Assets/Player Controller/input action map.inputactions
Monster Mash/Monster Mash/Assets/Scripts/MultiplayerScripts/CharacterSelectIcon.cs
Monster Mash/Monster Mash/Assets/Scripts/MultiplayerScripts/MultiplayerCursor.cs
Monster Mash/Monster Mash/Assets/Scripts/MultiplayerScripts/MultiplayerJoinManager.cs
Monster Mash/Monster Mash/Assets/Scripts/MultiplayerScripts/PlayerSpawnManager.cs
Monster Mash/Monster Mash/Assets/Scripts/input_handler.cs

Weekly Updates to CSS and Level Select + Added Model moving from scene to scene

Updated CSS and Level Select

---

Monster Mash/Monster Mash/Assets/Monster Parts/Arms/Arm 4/Animations/Arm 4 - Downward Attack - Heavy.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Arms/Arm 4/Animations/Arm 4 - Downward Attack - Neutral.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Arms/Arm 4/Animations/Arm 4 - Downward Attack - Wind Up.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Arms/Arm 4/Animations/Arm 4 - Forward Attack - Heavy.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Arms/Arm 4/Animations/Arm 4 - Forward Attack - Neutral.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Arms/Arm 4/Animations/Arm 4 - Forward Attack - Wind Up.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Arms/Arm 4/Animations/Arm 4 - Upward Attack - Heavy.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Arms/Arm 4/Animations/Arm 4 - Upward Attack - Neutral.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Arms/Arm 4/Animations/Arm 4 - Upward Attack - Wind Up.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Arms/Arm 4/Animations/Arm 4.1.controller
Monster Mash/Monster Mash/Assets/Monster Parts/Arms/Arm 4/Animations/Arm 4.1.controller.meta
Monster Mash/Monster Mash/Assets/Monster Parts/Arms/Arm 4/Animations/Arm 4.controller
Monster Mash/Monster Mash/Assets/Test Rooms/Matt/MattsWorkshop.unity

*Added Rachel's animations to the rest of the Arm7 animator 
*Added Arm4 to Matt's workshop
*Added hurtboxes and components to Arm4
*Added Animations and keyframe triggers to Arm4 animator On a side note, colliders may need to be reviewed after seeing how the mesh behaves during the animations

Arm7 Animations & Arm4 Implementations

---

Monster Mash/Monster Mash/Assets/Test Rooms/Matt/MattsWorkshop.unity

*Added Arm4 & 7 to MattsWorkshop, attached them to monster to experiment 
*Put Rachel's animations in Animator (Created a 7.1 & 4.1 animators) 
*Added components and tags to monster parts
*Added keyframes to animations

Arm4 & Arm7 Implementation

---

Monster Mash/Monster Mash/Assets/BuildAScare.unity
Monster Mash/Monster Mash/Assets/Scripts/CameraRotZoom.cs
Monster Mash/Monster Mash/Assets/Scripts/LimbSelector.cs

Reverts GavinArechiga/Monster-Mash#87

Revert "update"

---

Monster Mash/Monster Mash/Assets/BuildAScare.unity
Monster Mash/Monster Mash/Assets/Scripts/CameraRotZoom.cs
Monster Mash/Monster Mash/Assets/Scripts/LimbSelector.cs

Limbs were given parents as a source or rotation.
Limbs are attaching semi correctly.
Limbs with multiple colliders are still having issues.

Parts are rotating correctly

---

Monster Mash/Monster Mash/Assets/Scripts/Controller2D.cs
Monster Mash/Monster Mash/Assets/Test Rooms/Judah/NewController.unity
Monster Mash/Monster Mash/ProjectSettings/TagManager.asset

-slope fixes
-edge detection
-rotation fixes
still slope bugs ://

A lotta fixes

---

Monster Mash/Monster Mash/Assets/Stages/13. Block Party/Black.mat
Monster Mash/Monster Mash/Assets/Stages/13. Block Party/Black.mat.meta
Monster Mash/Monster Mash/Assets/Stages/13. Block Party/Block Party.unity
Monster Mash/Monster Mash/Assets/Stages/13. Block Party/Brown.mat
Monster Mash/Monster Mash/Assets/Stages/13. Block Party/Brown.mat.meta
Monster Mash/Monster Mash/Assets/Stages/13. Block Party/New Material 1.mat
Monster Mash/Monster Mash/Assets/Stages/13. Block Party/New Material 1.mat.meta
Monster Mash/Monster Mash/Assets/Stages/13. Block Party/New Material.mat
Monster Mash/Monster Mash/Assets/Stages/13. Block Party/New Material.mat.meta
Monster Mash/Monster Mash/Assets/Stages/13. Block Party/Red.mat
Monster Mash/Monster Mash/Assets/Stages/13. Block Party/Red.mat.meta
Monster Mash/Monster Mash/Assets/Stages/13. Block Party/WHite.mat
Monster Mash/Monster Mash/Assets/Stages/13. Block Party/WHite.mat.meta

Added a little more grayboxing into Block Party, giving some reference for environmental objects and scale.

Block Party Graybox

---

Monster Mash/Monster Mash/Assets/Scripts/Controller2D.cs
Monster Mash/Monster Mash/Assets/Scripts/input_handler.cs
Monster Mash/Monster Mash/Assets/Test Rooms/Judah/NewController.unity

controller fixed
jumping fixed
movement fixed
:-)

jumping fixed

---

Monster Mash/Monster Mash/ProjectSettings/EditorBuildSettings.asset

This is just for the scene in my folder

More Scene Movement

---

Monster Mash/Monster Mash/Assets/Resources/Fun-Test Parts/Monster/NoLongerPlayer.prefab
Monster Mash/Monster Mash/Assets/Resources/Fun-Test Parts/Monster/NoLongerPlayer.prefab.meta
Monster Mash/Monster Mash/Assets/Resources/Fun-Test Parts/Monster/Player.prefab
Monster Mash/Monster Mash/Assets/Scripts/Controller2D.cs
Monster Mash/Monster Mash/Assets/Test Rooms/Judah/NewController.unity

that fella moved! just like them vidjyagames
Jeremy's test room for the FunTest now includes a stunning lil fella.
still has bugs:
-animated legs dont realize they're on the ground so wont walk
-VFX dont match model location and size
-ya boy who is me still has to program in more animations to trigger when they need to

IT'S ALIIIIIIIIVE!!!!

---

Monster Mash/Monster Mash/Assets/Resources/Fun-Test Parts/Monster/Player.prefab

increased jump height for fun test demo

Jump height

---

Monster Mash/Monster Mash/Assets/Player Controller/input action map.inputactions

added supported controllers,
removed additional XBOX control scheme

changed controllers

---

Monster Mash/Monster Mash/Assets/Player Controller/Grounded Limb Area.prefab
Monster Mash/Monster Mash/Assets/Player Controller/Grounded Limb Area.prefab.meta
Monster Mash/Monster Mash/Assets/Resources/Fun-Test Parts/Monster/MonsterEmpty.prefab

Adjusted Monster Controller

---

Monster Mash/Monster Mash/Assets/Stages/14. Beastdome.meta
Monster Mash/Monster Mash/Assets/Stages/14. Beastdome/Beastdome.unity
Monster Mash/Monster Mash/Assets/Stages/14. Beastdome/Beastdome.unity.meta
Monster Mash/Monster Mash/Assets/Stages/14. Beastdome/Material.meta
Monster Mash/Monster Mash/Assets/Stages/14. Beastdome/Material/Black.mat
Monster Mash/Monster Mash/Assets/Stages/14. Beastdome/Material/Black.mat.meta
Monster Mash/Monster Mash/Assets/Stages/14. Beastdome/Material/Blue.mat
Monster Mash/Monster Mash/Assets/Stages/14. Beastdome/Material/Blue.mat.meta
Monster Mash/Monster Mash/Assets/Stages/14. Beastdome/Material/Brown.mat
Monster Mash/Monster Mash/Assets/Stages/14. Beastdome/Material/Brown.mat.meta
Monster Mash/Monster Mash/Assets/Stages/14. Beastdome/Material/Clear.mat
Monster Mash/Monster Mash/Assets/Stages/14. Beastdome/Material/Clear.mat.meta
Monster Mash/Monster Mash/Assets/Stages/14. Beastdome/Material/Light Brown.mat
Monster Mash/Monster Mash/Assets/Stages/14. Beastdome/Material/Light Brown.mat.meta
Monster Mash/Monster Mash/Assets/Stages/14. Beastdome/Material/New Material.mat
Monster Mash/Monster Mash/Assets/Stages/14. Beastdome/Material/New Material.mat.meta
Monster Mash/Monster Mash/Assets/Stages/14. Beastdome/Material/Red.mat
Monster Mash/Monster Mash/Assets/Stages/14. Beastdome/Material/Red.mat.meta
Monster Mash/Monster Mash/Assets/Stages/14. Beastdome/Material/Yellow.mat
Monster Mash/Monster Mash/Assets/Stages/14. Beastdome/Material/Yellow.mat.meta

Uploading the first graybox concept of the beastdome

Beastdome Graybox

---

Monster Mash/Monster Mash/Assets/Monster Parts/Tails/Tail 4/Animations/Tail 4 - Backward Attack - Heavy.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Tails/Tail 4/Animations/Tail 4 - Backward Attack - Neutral.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Tails/Tail 4/Animations/Tail 4 - Backward Attack - Wind Up.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Tails/Tail 4/Animations/Tail 4 - Downward Attack - Heavy.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Tails/Tail 4/Animations/Tail 4 - Downward Attack - Neutral.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Tails/Tail 4/Animations/Tail 4 - Downward Attack - Wind Up.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Tails/Tail 4/Animations/Tail 4 - Upward Attack - Heavy.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Tails/Tail 4/Animations/Tail 4 - Upward Attack - Neutral.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Tails/Tail 4/Animations/Tail 4 - Upward Attack - Wind Up.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Tails/Tail 4/Animations/Tail 4.controller
Monster Mash/Monster Mash/Assets/Monster Parts/Tails/Tail 4/INK_DROPLETS (UNIVERSAL)/Ink_Droplet_1_Textures/Ink_Droplet_1_Ink_Droplet_1_MAT_Normal.png.meta
Monster Mash/Monster Mash/Assets/Monster Parts/Tails/Tail 4/INK_DROPLETS (UNIVERSAL)/Ink_Droplet_1_Textures/Materials.meta
Monster Mash/Monster Mash/Assets/Monster Parts/Tails/Tail 4/INK_DROPLETS (UNIVERSAL)/Ink_Droplet_1_Textures/Materials/Ink_Droplet_1_Ink_Droplet_1_MAT_BaseColor.mat
Monster Mash/Monster Mash/Assets/Monster Parts/Tails/Tail 4/INK_DROPLETS (UNIVERSAL)/Ink_Droplet_1_Textures/Materials/Ink_Droplet_1_Ink_Droplet_1_MAT_BaseColor.mat.meta

redid the attacks
fixed neutral collision issue

Inky Tail Attacks Fixed

---

Monster Mash/Monster Mash/Assets/Monster Parts/projectile.cs

boomerangs are here!
still needs:
angles,
impact adjustment,
controlled lag frames between rangs

Added boomerangs to Projectile.cs

---

Monster Mash/Monster Mash/Assets/Monster Parts/Legs/Leg 2/Animations/Leg 2 - Backward Attack - Heavy Airborn.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Legs/Leg 2/Animations/Leg 2 - Backward Attack - Heavy Grounded.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Legs/Leg 2/Animations/Leg 2 - Downward Attack - Heavy Airborn.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Legs/Leg 2/Animations/Leg 2 - Downward Attack - Heavy Grounded.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Legs/Leg 2/Animations/Leg 2 - Forward Attack - Heavy Airborn.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Legs/Leg 2/Animations/Leg 2 - Forward Attack - Heavy Grounded.anim
Monster Mash/Monster Mash/Assets/Monster Parts/monsterPart.cs
Monster Mash/Monster Mash/Assets/Monster Parts/monsterPartReference.cs
Monster Mash/Monster Mash/Assets/Monster Parts/projectile.cs
Monster Mash/Monster Mash/Assets/Monster Parts/vfxHolder.cs

Boomerang 
-returns on hit
-can be angled
-wolf leg set up
-set as boomerang attack on monsterpart
bad:
-reload mechanic really difficult
-some directional attack weird stuff

More boomrang

---

Monster Mash/Monster Mash/Assets/Scripts/FpsCounter.cs
Monster Mash/Monster Mash/Assets/Scripts/FpsCounter.cs.meta
Monster Mash/Monster Mash/Assets/Stages/13. Block Party/BlockPartyStage.unitypackage.meta

Organized block party hierarchy and added an FPS counter to block party and Greenhouse

Block Party Hierarchy Organizing

---

Monster Mash/Monster Mash/Assets/Monster Parts/projectile.cs

boomerang FINALLY works
oh my goodnees
-fixed sandal visual for leg 2
-boomerang returns correctly
-enlarged sandal projecitle size

Mah branch

---

Monster Mash/Monster Mash/Assets/VFX/Confetti FX 2/Upgrade/Confetti FX 2 URP Upgrade (2019.3.1f1).unitypackage.meta
Monster Mash/Monster Mash/Assets/VFX/Hovl Studio/Render Pipelines support/Solves transparent problem Unity 2020+ URPHS.unitypackage.meta
Monster Mash/Monster Mash/Assets/VFX/Hovl Studio/Render Pipelines support/Unity 2019.2+ HDRPHS.unitypackage.meta
Monster Mash/Monster Mash/Assets/VFX/Hovl Studio/Render Pipelines support/Unity 2019.2+ URPHS.unitypackage.meta
Monster Mash/Monster Mash/Assets/VFX/Hovl Studio/Render Pipelines support/Unity 2019.3+ HDRPHS.unitypackage.meta
Monster Mash/Monster Mash/Assets/VFX/Hovl Studio/Render Pipelines support/Unity 2019.3+ URPHS.unitypackage.meta
Monster Mash/Monster Mash/Assets/VFX/Hovl Studio/Render Pipelines support/Unity 2020+ HDRPHS.unitypackage.meta
Monster Mash/Monster Mash/Assets/VFX/Hovl Studio/Render Pipelines support/Unity 2020+ URPHS.unitypackage.meta

existing limbs resized, rotated
extra and old limbs removed

Workshop cleaned up

---

Monster Mash/Monster Mash/Assets/Monster Parts/MonsterCalculations.cs
Monster Mash/Monster Mash/Assets/Monster Parts/MonsterCalculations.cs.meta
Monster Mash/Monster Mash/Assets/Monster Parts/monsterPart.cs
Monster Mash/Monster Mash/Assets/Monster Parts/monsterPartReference.cs
Monster Mash/Monster Mash/Assets/VFX/Confetti FX 2/Upgrade/Confetti FX 2 URP Upgrade (2019.3.1f1).unitypackage.meta
Monster Mash/Monster Mash/Assets/VFX/Hovl Studio/Render Pipelines support/Solves transparent problem Unity 2020+ URPHS.unitypackage.meta
Monster Mash/Monster Mash/Assets/VFX/Hovl Studio/Render Pipelines support/Unity 2019.2+ HDRPHS.unitypackage.meta
Monster Mash/Monster Mash/Assets/VFX/Hovl Studio/Render Pipelines support/Unity 2019.2+ URPHS.unitypackage.meta
Monster Mash/Monster Mash/Assets/VFX/Hovl Studio/Render Pipelines support/Unity 2019.3+ HDRPHS.unitypackage.meta
Monster Mash/Monster Mash/Assets/VFX/Hovl Studio/Render Pipelines support/Unity 2019.3+ URPHS.unitypackage.meta
Monster Mash/Monster Mash/Assets/VFX/Hovl Studio/Render Pipelines support/Unity 2020+ HDRPHS.unitypackage.meta
Monster Mash/Monster Mash/Assets/VFX/Hovl Studio/Render Pipelines support/Unity 2020+ URPHS.unitypackage.meta

i hope any of this workd on jah
still optimizing
but the script is half the size it used to be at least

Script Shortened

---

Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 6/Animations.meta
Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 6/Animations/Wing 6 - Big Flap.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 6/Animations/Wing 6 - Big Flap.anim.meta
Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 6/Animations/Wing 6 - Brace.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 6/Animations/Wing 6 - Brace.anim.meta
Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 6/Animations/Wing 6 - Fall.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 6/Animations/Wing 6 - Fall.anim.meta
Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 6/Animations/Wing 6 - Glide.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 6/Animations/Wing 6 - Glide.anim.meta
Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 6/Animations/Wing 6 - Idle Fly.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 6/Animations/Wing 6 - Idle Fly.anim.meta
Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 6/Animations/Wing 6 - Idle Grounded.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 6/Animations/Wing 6 - Idle Grounded.anim.meta
Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 6/Animations/Wing 6 - Jump.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 6/Animations/Wing 6 - Jump.anim.meta
Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 6/Animations/Wing 6 - Land.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 6/Animations/Wing 6 - Land.anim.meta
Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 6/Animations/Wing 6 - Running.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 6/Animations/Wing 6 - Running.anim.meta
Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 6/Animations/Wing 6 - Soft Landing.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 6/Animations/Wing 6 - Soft Landing.anim.meta
Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 6/Animations/Wing 6 - Tuck In.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 6/Animations/Wing 6 - Tuck In.anim.meta
Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 6/Animations/Wing 6.controller
Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing 6/Animations/Wing 6.controller.meta
Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing Template.controller
Monster Mash/Monster Mash/Assets/Monster Parts/Wings/Wing Template.controller.meta
Monster Mash/Monster Mash/Assets/Resources/Build-A-Scare Parts/Wings/Wing 6.prefab

Completed the setup process for wing 6

Finished setup for wing 6

---

Monster Mash/Monster Mash/Assets/Resources/Build-A-Scare Parts/Wings/Wing 5.prefab

Reduced the number of colliders by using larger colliders for the wings

Added new colliders

---

Monster Mash/Monster Mash/Assets/Resources/Build-A-Scare Parts/Arms/Arm 5.prefab

Added colliders

---

Monster Mash/Monster Mash/Assets/Resources/Build-A-Scare Parts/Wings/Wing 1.prefab

Added colliders to wing 4(a.k.a wing 1)

Added colliders to wing 4(a.k.a wing 1)

---

Monster Mash/Monster Mash/Assets/Resources/Build-A-Scare Parts/Wings/Wing 4.prefab
Monster Mash/Monster Mash/Assets/VFX/Confetti FX 2/Upgrade/Confetti FX 2 URP Upgrade (2019.3.1f1).unitypackage.meta
Monster Mash/Monster Mash/Assets/VFX/Hovl Studio/Render Pipelines support/Solves transparent problem Unity 2020+ URPHS.unitypackage.meta
Monster Mash/Monster Mash/Assets/VFX/Hovl Studio/Render Pipelines support/Unity 2019.2+ HDRPHS.unitypackage.meta
Monster Mash/Monster Mash/Assets/VFX/Hovl Studio/Render Pipelines support/Unity 2019.2+ URPHS.unitypackage.meta
Monster Mash/Monster Mash/Assets/VFX/Hovl Studio/Render Pipelines support/Unity 2019.3+ HDRPHS.unitypackage.meta
Monster Mash/Monster Mash/Assets/VFX/Hovl Studio/Render Pipelines support/Unity 2019.3+ URPHS.unitypackage.meta
Monster Mash/Monster Mash/Assets/VFX/Hovl Studio/Render Pipelines support/Unity 2020+ HDRPHS.unitypackage.meta
Monster Mash/Monster Mash/Assets/VFX/Hovl Studio/Render Pipelines support/Unity 2020+ URPHS.unitypackage.meta

Added the hurt boxes on the fixed prefab and also added a rigidbody component which was missing

Added colliders back

---

Monster Mash/Monster Mash/Assets/Resources/Build-A-Scare Parts/Torsos/Torso 12.prefab

Went through the entire checklist for torso 12

Torso 12 Setup

---

Monster Mash/Monster Mash/Assets/Resources/Build-A-Scare Parts/Torsos/Torso 13.prefab

Went through the entire setup checklist for torso 13

Finished torso 13 setup

---

Monster Mash/Monster Mash/Assets/Resources/Build-A-Scare Parts/Torsos/Torso 14.prefab

Went through the setup checklist for torso 14

Completed setup for torso 14

---

Monster Mash/Monster Mash/Assets/Resources/Build-A-Scare Parts/Torsos/Torso 16.prefab

Went through the checklist for torso 16

Finished Torso 16 Setup

---

Monster Mash/Monster Mash/Assets/Resources/Build-A-Scare Parts/Torsos/Torso 14.prefab
Monster Mash/Monster Mash/Assets/Resources/Build-A-Scare Parts/Torsos/Torso 16.prefab
Monster Mash/Monster Mash/Assets/Resources/Build-A-Scare Parts/Torsos/Torso 17.prefab

completed torso 17 checklist and also fixed missed steps from other torso's

Finished Torso 17 setup

---

Monster Mash/Monster Mash/Assets/Resources/Build-A-Scare Parts/Torsos/Torso 12.prefab
Monster Mash/Monster Mash/Assets/Resources/Build-A-Scare Parts/Torsos/Torso 15.prefab
Monster Mash/Monster Mash/Assets/Resources/Build-A-Scare Parts/Torsos/Torso 16.prefab
Monster Mash/Monster Mash/Assets/Resources/Build-A-Scare Parts/Torsos/Torso 17.prefab
Monster Mash/Monster Mash/Assets/Resources/Build-A-Scare Parts/Torsos/Torso 18.prefab
Monster Mash/Monster Mash/Assets/Resources/Build-A-Scare Parts/Torsos/Torso 19.prefab

Finished setting up torso 19 and also fixed neck collider being off on other torso's

Finished torso 19

---

Monster Mash/Monster Mash/Assets/Resources/Build-A-Scare Parts/Torsos/Torso 20.prefab

Finished the setup for torso 20

Finished torso 20 setup

---

Monster Mash/Monster Mash/Assets/Test Rooms/Connor.meta
Monster Mash/Monster Mash/Assets/Test Rooms/Connor/Connor Testing Room.unity
Monster Mash/Monster Mash/Assets/Test Rooms/Connor/Connor Testing Room.unity.meta
Monster Mash/Monster Mash/Assets/VFX/Confetti FX 2/Upgrade/Confetti FX 2 URP Upgrade (2019.3.1f1).unitypackage.meta
Monster Mash/Monster Mash/Assets/VFX/Hovl Studio/Render Pipelines support/Solves transparent problem Unity 2020+ URPHS.unitypackage.meta
Monster Mash/Monster Mash/Assets/VFX/Hovl Studio/Render Pipelines support/Unity 2019.2+ URPHS.unitypackage.meta
Monster Mash/Monster Mash/Assets/VFX/Hovl Studio/Render Pipelines support/Unity 2019.3+ URPHS.unitypackage.meta
Monster Mash/Monster Mash/Assets/VFX/Hovl Studio/Render Pipelines support/Unity 2020+ HDRPHS.unitypackage.meta
Monster Mash/Monster Mash/Assets/VFX/Hovl Studio/Render Pipelines support/Unity 2020+ URPHS.unitypackage.meta

Created a new folder called "Connor" and added a testing scene in it.

Connor Test Room

---

Monster Mash/Monster Mash/Assets/Resources/Build-A-Scare Parts/Heads/Head 4.prefab

Went through the checklist and setup head 4

Completed Setup for head 4

---

Monster Mash/Monster Mash/Assets/Resources/Build-A-Scare Parts/Heads/Head 4.prefab
Monster Mash/Monster Mash/Assets/Resources/Build-A-Scare Parts/Heads/Head 5.prefab

Head 5 setup

---

Monster Mash/Monster Mash/Assets/Resources/Build-A-Scare Parts/Heads/Head 6.prefab

Head 6 Setup

---

Monster Mash/Monster Mash/Assets/Monster Parts/Horns/Horn 1/Horn 1 - Heavy.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Horns/Horn 1/Horn 1 - Heavy.anim.meta
Monster Mash/Monster Mash/Assets/Monster Parts/Horns/Horn 1/Horn 1 - Idle.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Horns/Horn 1/Horn 1 - Idle.anim.meta
Monster Mash/Monster Mash/Assets/Monster Parts/Horns/Horn 1/Horn 1 - Neutral.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Horns/Horn 1/Horn 1 - Neutral.anim.meta
Monster Mash/Monster Mash/Assets/Monster Parts/Horns/Horn 1/Horn 1 - Wind Up.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Horns/Horn 1/Horn 1 - Wind Up.anim.meta
Monster Mash/Monster Mash/Assets/Monster Parts/Horns/Horn 1/Horn 1.controller
Monster Mash/Monster Mash/Assets/Monster Parts/Horns/Horn 1/Horn 1.controller.meta
Monster Mash/Monster Mash/Assets/Resources/Build-A-Scare Parts/Horns/Horn 1.prefab

Horn 1 Setup

---

Monster Mash/Monster Mash/Assets/Monster Parts/Horns/Horn 1/Horn 1 - Idle.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Horns/Horn 1/Horn 1 - Neutral.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Horns/Horn 1/Horn 1 - Wind Up.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Horns/Horn 5/Horn 5 - Heavy.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Horns/Horn 5/Horn 5 - Heavy.anim.meta
Monster Mash/Monster Mash/Assets/Monster Parts/Horns/Horn 5/Horn 5 - Idle.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Horns/Horn 5/Horn 5 - Idle.anim.meta
Monster Mash/Monster Mash/Assets/Monster Parts/Horns/Horn 5/Horn 5 - Neutral.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Horns/Horn 5/Horn 5 - Neutral.anim.meta
Monster Mash/Monster Mash/Assets/Monster Parts/Horns/Horn 5/Horn 5 - Wind Up.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Horns/Horn 5/Horn 5 - Wind Up.anim.meta
Monster Mash/Monster Mash/Assets/Monster Parts/Horns/Horn 5/Horn 5.controller
Monster Mash/Monster Mash/Assets/Monster Parts/Horns/Horn 5/Horn 5.controller.meta
Monster Mash/Monster Mash/Assets/Resources/Build-A-Scare Parts/Horns/Horn5.prefab

Setup horn 1 and fixed an issue with horn 1 where the animations were not assigned to the animation controller and the animations events didn't save from when I initially worked on horn 1

Horn 5 Setup & Horn 1 Fixes

---

Monster Mash/Monster Mash/Assets/Resources/Build-A-Scare Parts/Torsos/Torso 2.prefab

Torso 2 Setup

---

Monster Mash/Monster Mash/Assets/Resources/Build-A-Scare Parts/Heads/Head 4.prefab
Monster Mash/Monster Mash/Assets/Resources/Build-A-Scare Parts/Heads/Head 5.prefab

Reverts GavinArechiga/Monster-Mash#220

Revert "Revert "Head 5 setup""

---

Monster Mash/Monster Mash/Assets/Resources/Build-A-Scare Parts/Torsos/Torso 8.prefab

Torso 8 Setup

---

Monster Mash/Monster Mash/Assets/Monster Parts/Decor/Decor 1/Decor 1 - Idle.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Decor/Decor 1/Decor 1 - Idle.anim.meta
Monster Mash/Monster Mash/Assets/Monster Parts/Decor/Decor 1/Decor 1.controller
Monster Mash/Monster Mash/Assets/Monster Parts/Decor/Decor 1/Decor 1.controller.meta
Monster Mash/Monster Mash/Assets/Resources/Build-A-Scare Parts/Decor/Decor 1.prefab
Monster Mash/Monster Mash/Assets/Resources/Build-A-Scare Parts/Torsos/Torso 8.prefab

Finished the setup for decor 1 and also fixed the tag on torso 8 which I forgot to set in my previous push

Decor 1 Setup

---

Monster Mash/Monster Mash/Assets/Resources/Build-A-Scare Parts/Heads/Head 11.prefab
Monster Mash/Monster Mash/Assets/Resources/Build-A-Scare Parts/Heads/Head 14.prefab
Monster Mash/Monster Mash/Assets/Resources/Build-A-Scare Parts/Heads/Head 4.prefab
Monster Mash/Monster Mash/Assets/Resources/Build-A-Scare Parts/Heads/Head 5.prefab
Monster Mash/Monster Mash/Assets/Resources/Build-A-Scare Parts/Heads/Head 6.prefab

Moved the sphere colliders on the heads up which fixed the issue of them not connecting to the neck connection

Fixed Head connections

---

Monster Mash/Monster Mash/Assets/Resources/Build-A-Scare Parts/Torsos/Torso 12.prefab
Monster Mash/Monster Mash/Assets/Resources/Build-A-Scare Parts/Torsos/Torso 13.prefab
Monster Mash/Monster Mash/Assets/Resources/Build-A-Scare Parts/Torsos/Torso 14.prefab
Monster Mash/Monster Mash/Assets/Resources/Build-A-Scare Parts/Torsos/Torso 15.prefab
Monster Mash/Monster Mash/Assets/Resources/Build-A-Scare Parts/Torsos/Torso 16.prefab
Monster Mash/Monster Mash/Assets/Resources/Build-A-Scare Parts/Torsos/Torso 17.prefab
Monster Mash/Monster Mash/Assets/Resources/Build-A-Scare Parts/Torsos/Torso 18.prefab
Monster Mash/Monster Mash/Assets/Resources/Build-A-Scare Parts/Torsos/Torso 19.prefab
Monster Mash/Monster Mash/Assets/Resources/Build-A-Scare Parts/Torsos/Torso 20.prefab

Restructured torso prefabs to match structure required by the animations

Fixed torso animations

---

Monster Mash/Monster Mash/Assets/Resources/Build-A-Scare Parts/Arms/Arm 12.prefab

The hit boxes were not tagged which is why the mesh renderer was appearing

Fixed mesh renderer appearing after dashing

---

Monster Mash/Monster Mash/Assets/Monster Parts/Tails/Tail 2/Animations/Tail 2.controller
Monster Mash/Monster Mash/Assets/Monster Parts/Tails/Tail 7/Animations/Tail 7 - Downward Attack - Heavy 2.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Tails/Tail 7/Animations/Tail 7 - Downward Attack - Heavy 2.anim.meta
Monster Mash/Monster Mash/Assets/Monster Parts/Tails/Tail 7/Animations/Tail 7 - Upward Attack - Heavy 2.anim
Monster Mash/Monster Mash/Assets/Monster Parts/Tails/Tail 7/Animations/Tail 7 - Upward Attack - Heavy 2.anim.meta
Monster Mash/Monster Mash/Assets/Monster Parts/Tails/Tail 7/Animations/Tail 7.controller
Monster Mash/Monster Mash/Assets/Resources/Build-A-Scare Parts/Tails/Tail 7.prefab

Some clips in the animation controller were not assigned

Fixed Tail 2

---

Monster Mash/Monster Mash/Assets/Monster Parts/Tails/Tail 7/Animations/Tail 7.controller

Addressed issues and bugs coming from Tail 7 attacks (issue found in controller transitions)

Fixes to Tail 7

---

Monster Mash/Monster Mash/Assets/Monster Parts/Legs/Leg 1/Animations/Old Animations/Leg 1 - Forward Brace.anim.meta
Monster Mash/Monster Mash/Assets/Resources/Build-A-Scare Parts/Legs/Leg 1.prefab

Leg idle doesn't look right during gameplay will have to investigate later

Adjusted hurt colliders

---

Monster Mash/Monster Mash/Assets/Resources/Build-A-Scare Parts/Legs/Leg 6.prefab

Okay nevermind I found the issue. It was a misnamed object in the heirarchy

Leg 6 ACTUAL fix

---

Monster Mash/Monster Mash/Assets/Resources/Build-A-Scare Parts/Arms/Arm 6.prefab

Arm 6 was already setup so I just looked it over and everything seemed fine

Checked Arm 6 for issues

---

Monster Mash/Monster Mash/Assets/Resources/Build-A-Scare Parts/Arms/Arm 7.prefab
Monster Mash/Monster Mash/Assets/Resources/Build-A-Scare Parts/Arms/Arm 9.prefab

Setup arm 9 and fixed the hitboxes on arm 7 to better fit the attacks

Setup arm 9 & fixed arm 7 hitboxes

---

Monster Mash/Monster Mash/Assets/Stages/3. Block Party/Foam Blocks/Blue Foam 1.mat
Monster Mash/Monster Mash/Assets/Stages/3. Block Party/Foam Blocks/Blue Foam 1.mat.meta
Monster Mash/Monster Mash/Assets/VFX/Confetti FX 2/Upgrade/Confetti FX 2 URP Upgrade (2019.3.1f1).unitypackage.meta
Monster Mash/Monster Mash/Assets/VFX/Hovl Studio/Render Pipelines support/Solves transparent problem Unity 2020+ URPHS.unitypackage.meta
Monster Mash/Monster Mash/Assets/VFX/Hovl Studio/Render Pipelines support/Unity 2019.2+ URPHS.unitypackage.meta
Monster Mash/Monster Mash/Assets/VFX/Hovl Studio/Render Pipelines support/Unity 2019.3+ HDRPHS.unitypackage.meta
Monster Mash/Monster Mash/Assets/VFX/Hovl Studio/Render Pipelines support/Unity 2019.3+ URPHS.unitypackage.meta
Monster Mash/Monster Mash/Assets/VFX/Hovl Studio/Render Pipelines support/Unity 2020+ HDRPHS.unitypackage.meta
Monster Mash/Monster Mash/Assets/VFX/Hovl Studio/Render Pipelines support/Unity 2020+ URPHS.unitypackage.meta

I FORGOT TO REMOVE THE PIPELINE RENDERER ISSUES IM SUPPOSED TO DELETE ON MY END BEFORE PUSHING.
I don't remember how this gets resolved if it's as simple as just removing them from the list of changes I've made since I don't think I can do anything on my end. Apologies.

Matt branch

---

Monster Mash/Monster Mash/Assets/Stages/13. Block Party/BlockPartyStage.unitypackage.meta
Monster Mash/Monster Mash/Assets/Stages/3. Block Party/Block Party V2.unity.meta
Monster Mash/Monster Mash/Assets/Stages/3. Block Party/Dragons/Materials.meta
Monster Mash/Monster Mash/Assets/Stages/3. Block Party/Dragons/Materials/Dragon_Green_AlbedoTransparency.mat
Monster Mash/Monster Mash/Assets/Stages/3. Block Party/Dragons/Materials/Dragon_Green_AlbedoTransparency.mat.meta
Monster Mash/Monster Mash/Assets/Stages/3. Block Party/FightingStageAnim.controller
Monster Mash/Monster Mash/Assets/Stages/3. Block Party/FightingStageAnim.controller.meta
Monster Mash/Monster Mash/Assets/Stages/3. Block Party/New Animation.anim
Monster Mash/Monster Mash/Assets/Stages/3. Block Party/New Animation.anim.meta

Added a new scene showing a second draft of Stage A for Block Party

Block Party Stage A New Draft

---

Monster Mash/Monster Mash/Assets/Stages/3. Block Party/BP SB GB2.unity.meta
Monster Mash/Monster Mash/Assets/Stages/3. Block Party/Block Party Stage B Greybox 2.unity.meta

Deletion of BP SB GB2 and adding/duplication of new scene of Block Party Stage B Greybox 2

Greybox 2 changes

---

Monster Mash/Monster Mash/Assets/Stages/13. Block Party/BlockPartyStage.unitypackage.meta

Creation of a new Branch and the actual deletion of BP SB GB2

New Branch + Actually deletion

---

Monster Mash/Monster Mash/Assets/Stages/3. Monsterberry Munch Mania/Monsterberry Munch Mania 1.unity

Updated the sandcastle of scene 1 in MMM

Sandcastle Update

---

Monster Mash/Monster Mash/Assets/Fantasy Skybox/Cubemaps/FS003/FS003_Night_Moonless_Cubemap.mat
Monster Mash/Monster Mash/Assets/Fantasy Skybox/Cubemaps/FS003/FS003_Rainy_Cubemap.mat
Monster Mash/Monster Mash/Assets/Fantasy Skybox/Cubemaps/FS003/FS003_Sunset_Cubemap 1.mat
Monster Mash/Monster Mash/Assets/Fantasy Skybox/Cubemaps/FS003/FS003_Sunset_Cubemap 1.mat.meta
Monster Mash/Monster Mash/Assets/Fantasy Skybox/Cubemaps/FS003/Night.mat
Monster Mash/Monster Mash/Assets/Fantasy Skybox/Cubemaps/FS003/Night.mat.meta
Monster Mash/Monster Mash/Assets/Fantasy Skybox/Cubemaps/FS003/galaxy_2.1_texture.png.meta
Monster Mash/Monster Mash/Assets/Stages/14. Beastdome/Camera Man Platform/CameraManPlatform 1.mat
Monster Mash/Monster Mash/Assets/Stages/14. Beastdome/Camera Man Platform/CameraManPlatform 1.mat.meta
Monster Mash/Monster Mash/Assets/Stages/14. Beastdome/Drone Spotlight/Drone Emission.mat
Monster Mash/Monster Mash/Assets/Stages/14. Beastdome/Drone Spotlight/Drone Spotlight MAT 1.mat
Monster Mash/Monster Mash/Assets/Stages/14. Beastdome/Drone Spotlight/Drone Spotlight MAT 1.mat.meta
Monster Mash/Monster Mash/Assets/Stages/14. Beastdome/Drone Spotlight/Drone Spotlight MAT.mat
Monster Mash/Monster Mash/Assets/Stages/14. Beastdome/Post Processing/Stage B - Post Processing Volume Profile.asset
Monster Mash/Monster Mash/Assets/Stages/14. Beastdome/Post Processing/Stage B - Post Processing Volume Profile.asset.meta
Monster Mash/Monster Mash/Assets/Stages/14. Beastdome/Stadium Lights.anim
Monster Mash/Monster Mash/Assets/Stages/14. Beastdome/Stadium Lights.anim.meta
Monster Mash/Monster Mash/Assets/Stages/14. Beastdome/Stage B Platform/Stage Platform no toon.mat
Monster Mash/Monster Mash/Assets/Stages/14. Beastdome/Stage B Platform/Stage Platform no toon.mat.meta
Monster Mash/Monster Mash/Assets/Stages/14. Beastdome/Stage B Platform/stageB_platform_MAT 1.mat

First art pass on Beastdome Stage B with material changes, lighting changes, volumetric lighting, animation, post processing, skyboxes, etc. included

Beastdome Stage B Art Pass

---

Monster Mash/Monster Mash/Assets/Stages/0. Hubworld/Hubworld.unity
Monster Mash/Monster Mash/Assets/Stages/0. Hubworld/Hubworld.unity.meta
Monster Mash/Monster Mash/Assets/UI/Slime Bottom.mat
Monster Mash/Monster Mash/Assets/UI/Slime Top.mat

Turned off mesh renderers for the greenhouse. Also added a new hubworld scene

Greenhouse Minor changes

---

Monster Mash/Monster Mash/Assets/Stages/0. Hubworld/Hubworld.unity

Hubworld Scale fix
Added Portal
Edit BaS

Hubworld Graybox pt3

---

Monster Mash/Monster Mash/Assets/Stages/0. Hubworld/Hubworld.unity

Added Basement
Added Training Room interior
Added interior decors

Hubworld Update

---

Monster Mash/Monster Mash/Assets/Stages/0. Hubworld/Hubworld.unity

Edited basement
- Scaled smaller
- Redesign decoration
- Added  Wine Cellar Redesign Training Room
- Remove Floating Platforms
- Added Set Design
- Added Elemental Chambers Redesign Observatory Archives
- Added Octopus/Tentacle Monster
- Added Projectors
- Redesign Elevator/Ladder

Update to Hubworld
